
name: Releasetest

# Controls when the workflow will run
on:
  # Triggers the workflow on push tags
#   push:
#     tags:
#       - 'v[0-9]+.[0-9]+.[0-9]+'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  RELEASE_ARTIFACTS_DIR: release-artifacts
  PUBLIC_REPO: jeffzheng0505/fireworksdk_ios_public

  PUBLIC_REPO_PATH: public_repo

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_artifactes:
    runs-on: macos-11
    steps:
    - name: Checkout
      env:
          mascot: Octocat
      run: |
        scripts_path=$PUBLIC_REPO_PATH/build
        echo "$scripts_path"
        echo 'Hi $env.mascot'
